# Generated by Django 4.0.3 on 2022-07-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='beverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=350)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('size', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ingredients', models.CharField(max_length=500)),
            ],
        ),
    ]
